apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-hw
  namespace: argocd 
spec:
  destination:
    namespace: argocd 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: golang_app/manifest
    repoURL: https://github.com/carlosp81/susecapt/
    targetRevision: HEAD
  syncPolicy: {}
