apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-hw
  name: golang-hw
  namespace: apps 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-hw
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: golang-hw
    spec:
      containers:
      - image: susecapt/go-helloworld:v1.0 
        imagePullPolicy: IfNotPresent
        name: go-helloworld
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
